import { db } from "../src/lib/db";
import { travelPackages } from "../src/lib/db/schema";

const packages = [
  // ── Jyotirlinga ─────────────────────────────────────────────
  {
    id: "tp_jyotirlinga_1",
    titleMr: "१२ ज्योतिर्लिंग संपूर्ण यात्रा",
    titleEn: "Complete 12 Jyotirlinga Yatra",
    descriptionMr: "भारतातील सर्व १२ ज्योतिर्लिंगांचे दर्शन एकाच यात्रेत. सोमनाथ, मल्लिकार्जुन, महाकालेश्वर, ओंकारेश्वर, केदारनाथ, भीमाशंकर, काशी विश्वनाथ, त्र्यंबकेश्वर, वैद्यनाथ, नागेश्वर, रामेश्वरम आणि घृष्णेश्वर — सर्व पवित्र स्थळांचा समावेश.",
    descriptionEn: "Visit all 12 Jyotirlingas in one journey. Somnath, Mallikarjun, Mahakaleshwar, Omkareshwar, Kedarnath, Bhimashankar, Kashi Vishwanath, Trimbakeshwar, Vaidyanath, Nageshwar, Rameshwaram and Grishneshwar — all sacred shrines included.",
    category: "jyotirlinga",
    duration: "18 दिवस / 17 रात्री",
    priceFrom: 45000,
    priceTo: 75000,
    inclusions: JSON.stringify(["AC बस प्रवास", "हॉटेल निवास", "सकाळचा नाश्ता व जेवण", "मंदिर दर्शन व्यवस्था", "अनुभवी गाईड", "प्रवास विमा"]),
    itineraryMr: "दिवस १: मुंबई → भीमाशंकर\nदिवस २: भीमाशंकर → त्र्यंबकेश्वर\nदिवस ३: त्र्यंबकेश्वर → घृष्णेश्वर (एलोरा)\nदिवस ४-५: ओंकारेश्वर → महाकालेश्वर (उज्जैन)\nदिवस ६-७: सोमनाथ → नागेश्वर\nदिवस ८-९: केदारनाथ\nदिवस १०-११: काशी विश्वनाथ → वैद्यनाथ\nदिवस १२-१४: मल्लिकार्जुन (श्रीशैलम)\nदिवस १५-१७: रामेश्वरम\nदिवस १८: परतीचा प्रवास",
    itineraryEn: "Day 1: Mumbai → Bhimashankar\nDay 2: Bhimashankar → Trimbakeshwar\nDay 3: Trimbakeshwar → Grishneshwar (Ellora)\nDay 4-5: Omkareshwar → Mahakaleshwar (Ujjain)\nDay 6-7: Somnath → Nageshwar\nDay 8-9: Kedarnath\nDay 10-11: Kashi Vishwanath → Vaidyanath\nDay 12-14: Mallikarjun (Srisailam)\nDay 15-17: Rameshwaram\nDay 18: Return journey",
    highlights: JSON.stringify(["सर्व १२ ज्योतिर्लिंग दर्शन", "अनुभवी पुजारी सोबत पूजा", "AC डिलक्स बस", "शुद्ध शाकाहारी जेवण"]),
    locationMr: "संपूर्ण भारत",
    locationEn: "Pan India",
    active: true,
    featured: true,
  },
  {
    id: "tp_jyotirlinga_2",
    titleMr: "पंचज्योतिर्लिंग महाराष्ट्र यात्रा",
    titleEn: "5 Jyotirlinga Maharashtra Yatra",
    descriptionMr: "महाराष्ट्रातील ५ ज्योतिर्लिंगांचे दर्शन — भीमाशंकर, त्र्यंबकेश्वर, घृष्णेश्वर, परळी वैद्यनाथ आणि औंढा नागनाथ. सोयीस्कर ४ दिवसांचा दौरा.",
    descriptionEn: "Visit 5 Jyotirlingas in Maharashtra — Bhimashankar, Trimbakeshwar, Grishneshwar, Parli Vaidyanath and Aundha Nagnath. Convenient 4-day tour.",
    category: "jyotirlinga",
    duration: "4 दिवस / 3 रात्री",
    priceFrom: 8500,
    priceTo: 14000,
    inclusions: JSON.stringify(["AC बस प्रवास", "हॉटेल निवास", "जेवण (सकाळ व रात्र)", "मंदिर दर्शन", "गाईड"]),
    highlights: JSON.stringify(["महाराष्ट्रातील ५ ज्योतिर्लिंगे", "सोयीस्कर ४ दिवसांचा दौरा", "पुण्याहून प्रस्थान"]),
    locationMr: "महाराष्ट्र",
    locationEn: "Maharashtra",
    active: true,
    featured: false,
  },

  // ── Char Dham ───────────────────────────────────────────────
  {
    id: "tp_chardham_1",
    titleMr: "चार धाम यात्रा — बद्रीनाथ, केदारनाथ, गंगोत्री, यमुनोत्री",
    titleEn: "Char Dham Yatra — Badrinath, Kedarnath, Gangotri, Yamunotri",
    descriptionMr: "उत्तराखंडातील पवित्र चार धाम यात्रा. बद्रीनाथ, केदारनाथ, गंगोत्री आणि यमुनोत्री या चार पवित्र धामांचे दर्शन. हिमालयातील निसर्गरम्य प्रवास आणि आध्यात्मिक अनुभव.",
    descriptionEn: "Sacred Char Dham pilgrimage in Uttarakhand. Visit Badrinath, Kedarnath, Gangotri and Yamunotri — four holy dhams. Scenic Himalayan journey with spiritual experience.",
    category: "char_dham",
    duration: "11 दिवस / 10 रात्री",
    priceFrom: 25000,
    priceTo: 45000,
    inclusions: JSON.stringify(["हरिद्वार ते हरिद्वार प्रवास", "हॉटेल/धर्मशाळा निवास", "जेवण (दिवसातून ३ वेळा)", "पोनी/पालखी (वैकल्पिक, अतिरिक्त शुल्क)", "अनुभवी गाईड", "प्राथमिक उपचार"]),
    itineraryMr: "दिवस १: हरिद्वार आगमन\nदिवस २: हरिद्वार → यमुनोत्री\nदिवस ३: यमुनोत्री दर्शन\nदिवस ४: यमुनोत्री → गंगोत्री\nदिवस ५: गंगोत्री दर्शन\nदिवस ६: गंगोत्री → गुप्तकाशी\nदिवस ७: गुप्तकाशी → केदारनाथ\nदिवस ८: केदारनाथ दर्शन → गुप्तकाशी\nदिवस ९: गुप्तकाशी → बद्रीनाथ\nदिवस १०: बद्रीनाथ दर्शन\nदिवस ११: बद्रीनाथ → हरिद्वार",
    itineraryEn: "Day 1: Arrive Haridwar\nDay 2: Haridwar → Yamunotri\nDay 3: Yamunotri Darshan\nDay 4: Yamunotri → Gangotri\nDay 5: Gangotri Darshan\nDay 6: Gangotri → Guptkashi\nDay 7: Guptkashi → Kedarnath\nDay 8: Kedarnath Darshan → Guptkashi\nDay 9: Guptkashi → Badrinath\nDay 10: Badrinath Darshan\nDay 11: Badrinath → Haridwar",
    highlights: JSON.stringify(["चार धाम संपूर्ण दर्शन", "हिमालयातील सुंदर निसर्ग", "गंगा-यमुना उगमस्थान भेट", "अनुभवी पंडित सोबत पूजा"]),
    locationMr: "उत्तराखंड",
    locationEn: "Uttarakhand",
    active: true,
    featured: true,
  },

  // ── Ashtavinayak ────────────────────────────────────────────
  {
    id: "tp_ashtavinayak_1",
    titleMr: "अष्टविनायक दर्शन — संपूर्ण ८ गणपती",
    titleEn: "Ashtavinayak Darshan — All 8 Ganapati Temples",
    descriptionMr: "महाराष्ट्रातील अष्टविनायक गणपतींचे संपूर्ण दर्शन. मोरगाव, सिद्धटेक, पाली, महड, थेऊर, लेण्याद्री, ओझर आणि रांजणगाव या ८ पवित्र गणपती मंदिरांना भेट द्या.",
    descriptionEn: "Complete Ashtavinayak Ganapati darshan in Maharashtra. Visit all 8 sacred Ganapati temples — Morgaon, Siddhatek, Pali, Mahad, Theur, Lenyadri, Ozar and Ranjangaon.",
    category: "ashtavinayak",
    duration: "2 दिवस / 1 रात्र",
    priceFrom: 3500,
    priceTo: 6000,
    inclusions: JSON.stringify(["AC बस प्रवास", "हॉटेल निवास (१ रात्र)", "सकाळचा नाश्ता व जेवण", "सर्व ८ मंदिर दर्शन", "गाईड"]),
    itineraryMr: "दिवस १: पुणे → मोरगाव → सिद्धटेक → पाली → महड (रात्री मुक्काम)\nदिवस २: थेऊर → लेण्याद्री → ओझर → रांजणगाव → पुणे परत",
    itineraryEn: "Day 1: Pune → Morgaon → Siddhatek → Pali → Mahad (night stay)\nDay 2: Theur → Lenyadri → Ozar → Ranjangaon → Return to Pune",
    highlights: JSON.stringify(["सर्व ८ गणपती एकाच यात्रेत", "पारंपरिक क्रमाने दर्शन", "पुण्याहून सोयीस्कर प्रवास", "नारळ प्रसाद समाविष्ट"]),
    locationMr: "पुणे विभाग, महाराष्ट्र",
    locationEn: "Pune Division, Maharashtra",
    active: true,
    featured: true,
  },

  // ── Shakti Peeth ────────────────────────────────────────────
  {
    id: "tp_shakti_1",
    titleMr: "५१ शक्तिपीठ दर्शन — प्रमुख शक्तिपीठे",
    titleEn: "51 Shakti Peeth Darshan — Major Shakti Peethas",
    descriptionMr: "भारतातील प्रमुख शक्तिपीठांचे दर्शन. कोल्हापूर महालक्ष्मी, तुळजापूर भवानी, माहूर रेणुकामाता, सप्तश्रुंगी आणि इतर प्रमुख देवी मंदिरे.",
    descriptionEn: "Visit major Shakti Peethas in India. Kolhapur Mahalakshmi, Tuljapur Bhavani, Mahur Renukamata, Saptashrungi and other important Devi temples.",
    category: "shakti_peeth",
    duration: "5 दिवस / 4 रात्री",
    priceFrom: 9000,
    priceTo: 15000,
    inclusions: JSON.stringify(["AC बस प्रवास", "हॉटेल निवास", "जेवण", "मंदिर दर्शन", "गाईड"]),
    highlights: JSON.stringify(["साडेतीन शक्तिपीठे", "कोल्हापूर महालक्ष्मी", "तुळजापूर भवानी", "माहूर रेणुकामाता"]),
    locationMr: "महाराष्ट्र",
    locationEn: "Maharashtra",
    active: true,
    featured: false,
  },
  {
    id: "tp_shakti_2",
    titleMr: "साडेतीन शक्तिपीठ यात्रा",
    titleEn: "3.5 Shakti Peeth Yatra (Maharashtra)",
    descriptionMr: "महाराष्ट्रातील साडेतीन शक्तिपीठांचे दर्शन — कोल्हापूर (महालक्ष्मी), तुळजापूर (भवानी), माहूर (रेणुकामाता) आणि वणी (सप्तश्रुंगी, अर्धपीठ). ही यात्रा अत्यंत पुण्यदायी मानली जाते.",
    descriptionEn: "Visit Maharashtra's 3.5 Shakti Peethas — Kolhapur (Mahalakshmi), Tuljapur (Bhavani), Mahur (Renukamata) and Vani (Saptashrungi, half peeth). This pilgrimage is considered highly auspicious.",
    category: "shakti_peeth",
    duration: "4 दिवस / 3 रात्री",
    priceFrom: 7500,
    priceTo: 12000,
    inclusions: JSON.stringify(["AC बस", "हॉटेल", "जेवण (३ वेळा)", "दर्शन व्यवस्था", "गाईड"]),
    highlights: JSON.stringify(["साडेतीन शक्तिपीठ संपूर्ण दर्शन", "विशेष पूजा व्यवस्था", "शुद्ध शाकाहारी भोजन"]),
    locationMr: "महाराष्ट्र",
    locationEn: "Maharashtra",
    active: true,
    featured: true,
  },

  // ── Datta Yatra ─────────────────────────────────────────────
  {
    id: "tp_datta_1",
    titleMr: "दत्त क्षेत्र यात्रा — गाणगापूर, नरसोबाची वाडी, औदुंबर",
    titleEn: "Datta Kshetra Yatra — Gangapur, Narsobachi Wadi, Audumbar",
    descriptionMr: "श्री दत्तात्रेयांच्या प्रमुख क्षेत्रांचे दर्शन. गाणगापूर, नरसोबाची वाडी, औदुंबर, कारंजा लाड आणि माहूर — सर्व दत्तस्थानांचा समावेश.",
    descriptionEn: "Visit major Dattatreya shrines. Gangapur, Narsobachi Wadi, Audumbar, Karanja Lad and Mahur — all Datta pilgrimage sites included.",
    category: "datta",
    duration: "4 दिवस / 3 रात्री",
    priceFrom: 7000,
    priceTo: 11000,
    inclusions: JSON.stringify(["AC बस प्रवास", "धर्मशाळा/हॉटेल निवास", "शुद्ध शाकाहारी जेवण", "दर्शन व्यवस्था", "गाईड"]),
    itineraryMr: "दिवस १: पुणे → गाणगापूर दर्शन\nदिवस २: गाणगापूर → नरसोबाची वाडी\nदिवस ३: नरसोबाची वाडी → औदुंबर → कारंजा लाड\nदिवस ४: माहूर दर्शन → पुणे परत",
    itineraryEn: "Day 1: Pune → Gangapur Darshan\nDay 2: Gangapur → Narsobachi Wadi\nDay 3: Narsobachi Wadi → Audumbar → Karanja Lad\nDay 4: Mahur Darshan → Return to Pune",
    highlights: JSON.stringify(["सर्व प्रमुख दत्तक्षेत्रे", "गाणगापूरला विशेष पूजा", "गुरुचरित्र पारायण", "शांत आध्यात्मिक वातावरण"]),
    locationMr: "महाराष्ट्र, कर्नाटक",
    locationEn: "Maharashtra, Karnataka",
    active: true,
    featured: false,
  },

  // ── Panch Kedar ─────────────────────────────────────────────
  {
    id: "tp_panchkedar_1",
    titleMr: "पंच केदार यात्रा — ५ शिव मंदिरे हिमालयात",
    titleEn: "Panch Kedar Yatra — 5 Shiva Temples in Himalayas",
    descriptionMr: "उत्तराखंडातील पंच केदार — केदारनाथ, तुंगनाथ, रुद्रनाथ, मध्यमहेश्वर आणि कल्पेश्वर. हिमालयातील या ५ प्राचीन शिव मंदिरांचे दर्शन हा अविस्मरणीय अनुभव आहे.",
    descriptionEn: "Panch Kedar in Uttarakhand — Kedarnath, Tungnath, Rudranath, Madhyamaheshwar and Kalpeshwar. Visit these 5 ancient Shiva temples in the Himalayas for an unforgettable spiritual experience.",
    category: "panch_kedar",
    duration: "14 दिवस / 13 रात्री",
    priceFrom: 35000,
    priceTo: 55000,
    inclusions: JSON.stringify(["हरिद्वार ते हरिद्वार प्रवास", "हॉटेल/गेस्टहाउस निवास", "जेवण", "ट्रेकिंग गाईड", "पोर्टर सेवा", "प्राथमिक उपचार किट"]),
    highlights: JSON.stringify(["५ प्राचीन शिव मंदिरे", "हिमालयातील ट्रेकिंग", "तुंगनाथ — जगातील सर्वोच्च शिव मंदिर", "निसर्गरम्य परिसर"]),
    locationMr: "उत्तराखंड",
    locationEn: "Uttarakhand",
    active: true,
    featured: false,
  },

  // ── Varanasi-Prayagraj ──────────────────────────────────────
  {
    id: "tp_varanasi_1",
    titleMr: "काशी-प्रयागराज-अयोध्या तीर्थयात्रा",
    titleEn: "Kashi-Prayagraj-Ayodhya Pilgrimage",
    descriptionMr: "काशी विश्वनाथ दर्शन, गंगा आरती, प्रयागराज संगम स्नान आणि अयोध्या श्रीराम मंदिर दर्शन. उत्तर भारतातील सर्वात पवित्र तीर्थक्षेत्रांचा अनुभव.",
    descriptionEn: "Kashi Vishwanath darshan, Ganga Aarti, Prayagraj Sangam bathing and Ayodhya Shri Ram Mandir darshan. Experience the holiest pilgrimage sites of North India.",
    category: "varanasi",
    duration: "5 दिवस / 4 रात्री",
    priceFrom: 12000,
    priceTo: 22000,
    inclusions: JSON.stringify(["ट्रेन/बस प्रवास", "हॉटेल निवास", "जेवण", "गंगा आरती", "नौका विहार", "मंदिर दर्शन", "स्थानिक गाईड"]),
    itineraryMr: "दिवस १: आगमन → काशी विश्वनाथ → गंगा आरती\nदिवस २: काशी मंदिरे → सारनाथ\nदिवस ३: काशी → प्रयागराज → संगम स्नान\nदिवस ४: प्रयागराज → अयोध्या → राम मंदिर\nदिवस ५: अयोध्या दर्शन → परत",
    itineraryEn: "Day 1: Arrival → Kashi Vishwanath → Ganga Aarti\nDay 2: Kashi temples → Sarnath\nDay 3: Kashi → Prayagraj → Sangam bathing\nDay 4: Prayagraj → Ayodhya → Ram Mandir\nDay 5: Ayodhya darshan → Return",
    highlights: JSON.stringify(["काशी विश्वनाथ दर्शन", "गंगा आरती अनुभव", "प्रयागराज संगम स्नान", "अयोध्या राम मंदिर"]),
    locationMr: "उत्तर प्रदेश",
    locationEn: "Uttar Pradesh",
    active: true,
    featured: true,
  },

  // ── Rameshwaram-Madurai ─────────────────────────────────────
  {
    id: "tp_rameshwaram_1",
    titleMr: "रामेश्वरम-मदुराई-कन्याकुमारी दर्शन",
    titleEn: "Rameshwaram-Madurai-Kanyakumari Darshan",
    descriptionMr: "दक्षिण भारतातील प्रमुख तीर्थक्षेत्रे — रामेश्वरम ज्योतिर्लिंग, मदुराई मीनाक्षी मंदिर आणि कन्याकुमारी. समुद्रकिनारी असलेल्या या पवित्र स्थळांचा अनोखा अनुभव.",
    descriptionEn: "Major pilgrimage sites of South India — Rameshwaram Jyotirlinga, Madurai Meenakshi Temple and Kanyakumari. Unique experience of these sacred coastal destinations.",
    category: "rameshwaram",
    duration: "5 दिवस / 4 रात्री",
    priceFrom: 14000,
    priceTo: 25000,
    inclusions: JSON.stringify(["ट्रेन/फ्लाईट", "हॉटेल निवास", "जेवण", "मंदिर दर्शन", "स्थानिक प्रवास", "गाईड"]),
    highlights: JSON.stringify(["रामेश्वरम ज्योतिर्लिंग", "२२ कुंड स्नान", "मदुराई मीनाक्षी मंदिर", "कन्याकुमारी सूर्योदय"]),
    locationMr: "तामिळनाडू",
    locationEn: "Tamil Nadu",
    active: true,
    featured: false,
  },

  // ── Dwarka-Somnath ──────────────────────────────────────────
  {
    id: "tp_dwarka_1",
    titleMr: "द्वारका-सोमनाथ-गिरनार यात्रा",
    titleEn: "Dwarka-Somnath-Girnar Yatra",
    descriptionMr: "गुजरातमधील पवित्र तीर्थक्षेत्रे — द्वारकाधीश मंदिर, सोमनाथ ज्योतिर्लिंग, नागेश्वर ज्योतिर्लिंग, गिरनार पर्वत आणि जुनागढ. भगवान श्रीकृष्णाच्या नगरीचे दर्शन.",
    descriptionEn: "Sacred pilgrimage sites in Gujarat — Dwarkadhish Temple, Somnath Jyotirlinga, Nageshwar Jyotirlinga, Girnar Mountain and Junagadh. Visit the city of Lord Krishna.",
    category: "dwarka",
    duration: "5 दिवस / 4 रात्री",
    priceFrom: 11000,
    priceTo: 20000,
    inclusions: JSON.stringify(["AC बस प्रवास", "हॉटेल निवास", "जेवण", "मंदिर दर्शन", "गाईड", "प्रवास विमा"]),
    highlights: JSON.stringify(["द्वारकाधीश दर्शन", "सोमनाथ ज्योतिर्लिंग", "नागेश्वर ज्योतिर्लिंग", "गिरनार दर्शन"]),
    locationMr: "गुजरात",
    locationEn: "Gujarat",
    active: true,
    featured: false,
  },

  // ── Shirdi-Shani Shingnapur ─────────────────────────────────
  {
    id: "tp_shirdi_1",
    titleMr: "शिर्डी-शनि शिंगणापूर-नाशिक दर्शन",
    titleEn: "Shirdi-Shani Shingnapur-Nashik Darshan",
    descriptionMr: "शिर्डी साईबाबा, शनि शिंगणापूर, नाशिक त्र्यंबकेश्वर आणि पंचवटी दर्शन. महाराष्ट्रातील सर्वात लोकप्रिय तीर्थयात्रा.",
    descriptionEn: "Shirdi Sai Baba, Shani Shingnapur, Nashik Trimbakeshwar and Panchavati darshan. Most popular pilgrimage in Maharashtra.",
    category: "shirdi",
    duration: "3 दिवस / 2 रात्री",
    priceFrom: 4500,
    priceTo: 8000,
    inclusions: JSON.stringify(["AC बस", "हॉटेल निवास", "जेवण", "VIP दर्शन पास", "गाईड"]),
    itineraryMr: "दिवस १: पुणे/मुंबई → शिर्डी → साईबाबा दर्शन → आरती\nदिवस २: शनि शिंगणापूर → नाशिक → त्र्यंबकेश्वर\nदिवस ३: पंचवटी दर्शन → कालाराम मंदिर → परत",
    itineraryEn: "Day 1: Pune/Mumbai → Shirdi → Sai Baba Darshan → Aarti\nDay 2: Shani Shingnapur → Nashik → Trimbakeshwar\nDay 3: Panchavati Darshan → Kalaram Temple → Return",
    highlights: JSON.stringify(["शिर्डी साईबाबा दर्शन", "शनि शिंगणापूर", "त्र्यंबकेश्वर ज्योतिर्लिंग", "पंचवटी दर्शन"]),
    locationMr: "महाराष्ट्र",
    locationEn: "Maharashtra",
    active: true,
    featured: true,
  },

  // ── Tirupati ────────────────────────────────────────────────
  {
    id: "tp_tirupati_1",
    titleMr: "तिरुपती बालाजी दर्शन — विशेष VIP पॅकेज",
    titleEn: "Tirupati Balaji Darshan — Special VIP Package",
    descriptionMr: "तिरुपती बालाजी (वेंकटेश्वर) दर्शन विशेष VIP व्यवस्थेसह. ३०० रुपयांचे दर्शन टिकीट, कल्याणम, प्रसादम आणि निवास व्यवस्था समाविष्ट.",
    descriptionEn: "Tirupati Balaji (Venkateswara) darshan with special VIP arrangement. Includes ₹300 darshan ticket, Kalyanam, Prasadam and accommodation.",
    category: "tirupati",
    duration: "3 दिवस / 2 रात्री",
    priceFrom: 8000,
    priceTo: 15000,
    inclusions: JSON.stringify(["फ्लाईट/ट्रेन टिकीट", "हॉटेल निवास", "दर्शन टिकीट", "प्रसादम", "स्थानिक प्रवास", "गाईड"]),
    highlights: JSON.stringify(["VIP दर्शन व्यवस्था", "कल्याणम सेवा", "लड्डू प्रसादम", "श्रीवारी मेट्टू मार्गे दर्शन"]),
    locationMr: "आंध्र प्रदेश",
    locationEn: "Andhra Pradesh",
    active: true,
    featured: false,
  },

  // ── Pandharpur Wari ─────────────────────────────────────────
  {
    id: "tp_pandharpur_1",
    titleMr: "पंढरपूर वारी — विठ्ठल दर्शन",
    titleEn: "Pandharpur Wari — Vitthal Darshan",
    descriptionMr: "पंढरपूर श्री विठ्ठल-रुक्मिणी दर्शन. आषाढी/कार्तिकी एकादशी विशेष यात्रा. पंढरपूर, तुळजापूर, अक्कलकोट स्वामी समर्थ मठ दर्शनासह.",
    descriptionEn: "Pandharpur Shri Vitthal-Rukmini darshan. Special Ashadhi/Kartiki Ekadashi tour. Includes Pandharpur, Tuljapur, Akkalkot Swami Samarth Math darshan.",
    category: "pandharpur",
    duration: "2 दिवस / 1 रात्र",
    priceFrom: 3000,
    priceTo: 5500,
    inclusions: JSON.stringify(["AC बस", "हॉटेल/धर्मशाळा", "जेवण", "दर्शन व्यवस्था"]),
    highlights: JSON.stringify(["विठ्ठल-रुक्मिणी दर्शन", "चंद्रभागा स्नान", "एकादशी विशेष पूजा", "अक्कलकोट दर्शन"]),
    locationMr: "सोलापूर, महाराष्ट्र",
    locationEn: "Solapur, Maharashtra",
    active: true,
    featured: false,
  },

  // ── Local Tours ─────────────────────────────────────────────
  {
    id: "tp_local_1",
    titleMr: "पुणे दर्शन — ८ मंदिरे एका दिवसात",
    titleEn: "Pune Darshan — 8 Temples in One Day",
    descriptionMr: "पुण्यातील ८ प्रसिद्ध मंदिरांचे एकदिवसीय दर्शन. पर्वती, दगडूशेठ गणपती, कसबा गणपती, श्रीमंत दगडूशेठ हलवाई, चतुःश्रुंगी, सारसबाग गणपती, पाताळेश्वर आणि भुलेश्वर.",
    descriptionEn: "One-day darshan of 8 famous temples in Pune. Parvati, Dagdusheth Ganpati, Kasba Ganpati, Chatushrungi, Sarasbaug Ganpati, Pataleshwar and Bhuleshwar.",
    category: "local",
    duration: "1 दिवस",
    priceFrom: 1200,
    priceTo: 2000,
    inclusions: JSON.stringify(["AC बस/कार", "सकाळचा नाश्ता", "सर्व मंदिर दर्शन", "गाईड"]),
    highlights: JSON.stringify(["८ प्रसिद्ध मंदिरे", "एकदिवसीय दौरा", "सोयीस्कर वेळापत्रक", "पुण्यातून प्रस्थान"]),
    locationMr: "पुणे",
    locationEn: "Pune",
    active: true,
    featured: false,
  },
  {
    id: "tp_local_2",
    titleMr: "मुंबई दर्शन — सिद्धिविनायक, महालक्ष्मी, हाजी अली",
    titleEn: "Mumbai Darshan — Siddhivinayak, Mahalakshmi, Haji Ali",
    descriptionMr: "मुंबईतील प्रसिद्ध धार्मिक स्थळांचे एकदिवसीय दर्शन. सिद्धिविनायक, महालक्ष्मी मंदिर, मुंबादेवी, बाबुलनाथ आणि हाजी अली.",
    descriptionEn: "One-day darshan of famous religious sites in Mumbai. Siddhivinayak, Mahalakshmi Temple, Mumbadevi, Babulnath and Haji Ali.",
    category: "local",
    duration: "1 दिवस",
    priceFrom: 1500,
    priceTo: 2500,
    inclusions: JSON.stringify(["AC कार/मिनी बस", "नाश्ता व जेवण", "सर्व मंदिर दर्शन", "गाईड"]),
    highlights: JSON.stringify(["सिद्धिविनायक दर्शन", "महालक्ष्मी मंदिर", "मुंबादेवी", "हाजी अली"]),
    locationMr: "मुंबई",
    locationEn: "Mumbai",
    active: true,
    featured: false,
  },

  // ── Custom Pilgrimage ───────────────────────────────────────
  {
    id: "tp_custom_1",
    titleMr: "सानुकूल तीर्थयात्रा — आपल्या आवडीनुसार",
    titleEn: "Custom Pilgrimage — As Per Your Preference",
    descriptionMr: "आपल्या आवडीनुसार खास तीर्थयात्रा पॅकेज. कुटुंब, मित्रमंडळ किंवा ग्रुप साठी विशेष व्यवस्था. तुमच्या बजेट आणि वेळापत्रकानुसार यात्रा तयार करू.",
    descriptionEn: "Custom pilgrimage package as per your preference. Special arrangements for family, friends or groups. We'll plan the journey according to your budget and schedule.",
    category: "custom",
    duration: "तुमच्या सोयीनुसार",
    priceFrom: 5000,
    priceTo: 100000,
    inclusions: JSON.stringify(["सानुकूल प्रवास व्यवस्था", "हॉटेल/धर्मशाळा निवास", "जेवण", "मंदिर दर्शन व्यवस्था", "गाईड", "प्रवास विमा"]),
    highlights: JSON.stringify(["आपल्या आवडीनुसार यात्रा", "कुटुंब/ग्रुप विशेष", "लवचिक वेळापत्रक", "सानुकूल बजेट"]),
    locationMr: "संपूर्ण भारत",
    locationEn: "Pan India",
    active: true,
    featured: false,
  },
];

async function seed() {
  console.log("Seeding travel packages...");
  for (const pkg of packages) {
    await db.insert(travelPackages).values(pkg as any).onConflictDoNothing();
    console.log(`  ✓ ${pkg.titleEn}`);
  }
  console.log(`\nDone! Seeded ${packages.length} travel packages.`);
}

seed().catch(console.error);
